int _putchar(char c);
void print_alphabet(void);
void print_alphabet_x10(void);
int _islower(int letter);
int _isalpha(int letter);
int print_sign(int number);
int _abs(int number);
int print_last_digit(int number);
void jack_bauer(void);
void times_table(void);
int add(int num1, int num2);
void print_to_98(int num);
